### test manipulate pure response with @Res() decorator
GET http://localhost:3000/test HTTP/1.1


### log original request object (from express) with @Req() decorator
GET http://localhost:3000/log-req HTTP/1.1

### log client's IP address with @Ip() decorator
GET http://localhost:3000/log-ip HTTP/1.1
